spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: currency-conversion
#  jpa:
#    show-sql: true
#    defer-datasource-initialization: true
#  datasource:
#    url: jdbc:h2:mem:testdb
#  h2:
#    console:
#      enabled: true
server:
  port: '8100'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
