spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: currency-exchange
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  retry:
    instances:
      sample-api:
        maxAttempts: 5
        waitDuration: 1s
        enableExponentialBackoff: true
#  circuitbreaker:
#    instances:
#      default:
#        failureRateThreshold: 90 #Se 90% das requisições falharem então mude o circuit breaker para aberto (Não manda requisição apenas a mensagem ou comportamento fallback direto)
  ratelimiter:
    instances:
      default:
#        2 request em 10s
        limitForPeriod: 2
        limitRefreshPeriod: 10s
  bulkhead:
    instances:
      default:
        maxConcurrentCalls: 10